// <auto-generated />
using BudgetManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BudgetManagementDbContext))]
    [Migration("20250818124449_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetManagement.Domain.Entities.BudgetRecord", b =>
                {
                    b.Property<string>("SubProjectCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("AdjustmentAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Agent")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ContractDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContractStatus")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ContractTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Contractor")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("CreditDeficitCommitment")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("CreditDeficitSupply")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("CreditNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("CurrentYearInvoicesAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("CurrentYearTotalCredit")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("EndDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExecutiveDept")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExtendedEndDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("InitialAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("MaxRequiredCredit")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Nature")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StartDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TotalContractAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("TotalCreditFromStart")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("TotalInvoicesAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("TotalWorkProgress")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("WorkReferralMethod")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("SubProjectCode");

                    b.ToTable("BudgetRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
